### ISSUE TITLE
Runtime Error: Shader version not supported

### ISSUE THREAD

**Issue by bakkdoor** [PistonDevelopers/Piston-Tutorials#1]
I followed the instructions of the tutorial, installed glfw using homebrew (running Mac OSX 10.9.4). Looks like the error is raised here:
https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/gl_back_end.rs#L105

Error output:

```
$ ./target/game
task '<main>' failed at 'compile_shader: ERROR: 0:2: '' :  version '330' is not supported
', src/gl_back_end.rs:105
```

Any thoughts?

**Comment by bvssvni** [comment]
This is outdated. Closing.
