### ISSUE TITLE
Can't compile Spinning Square

### ISSUE THREAD

**Issue by SJoshua** [PistonDevelopers/Piston-Tutorials#161]
<pre>
   Compiling num-iter v0.1.33
   Compiling num-rational v0.1.37
error[E0412]: cannot find type `BigInt` in this scope
   --> C:\Users\Joshua Astray\.cargo\registry\src\github.com-1ecc6299db9ec823\num-rational-0.1.37\src\lib.rs:671:30
    |
671 | impl FromPrimitive for Ratio< BigInt > {
    |                              ^^^^^^ not found in this scope

error: no associated item named `from_float` found for type `Ratio<_>` in the current scope
   --> C:\Users\Joshua Astray\.cargo\registry\src\github.com-1ecc6299db9ec823\num-rational-0.1.37\src\lib.rs:681:9
    |
681 |         Ratio::from_float(n)
    |         ^^^^^^^^^^^^^^^^^

error: no associated item named `from_float` found for type `Ratio<_>` in the current scope
   --> C:\Users\Joshua Astray\.cargo\registry\src\github.com-1ecc6299db9ec823\num-rational-0.1.37\src\lib.rs:685:9
    |
685 |         Ratio::from_float(n)
    |         ^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `num-rational`.
Build failed, waiting for other jobs to finish...
error: build failed
</pre>

How to solve?

**Comment by LaylConway** [comment]
This was a problem caused by a breaking change in num-rational. The version that caused this has been yanked.

**Comment by SJoshua** [comment]
It's okay now.
thx.
