### ISSUE TITLE
Missing import in chapter 4

### ISSUE THREAD

**Issue by GhostOfMe** [PistonDevelopers/Piston-Tutorials#171]
In chapter 4

> Import GameboardView in "main.rs":
`pub use gameboard::Gameboard;`
`pub use gameboard_controller::GameboardController;`
`pub use gameboard_view::GameboardView;`

I guess it should be:

`pub use gameboard::Gameboard;`
`pub use gameboard_controller::GameboardController;`
`pub use gameboard_view::{GameboardView, GameboardViewSettings};`

**Comment by bvssvni** [comment]
Thanks!
