### ISSUE TITLE
Sudoku tutorial: multiple digits drawn in a cell of the grid

### ISSUE THREAD

**Issue by JimmyHypi** [PistonDevelopers/Piston-Tutorials#225]
Hi,
in the Sudoku tutorial, when drawing a character from the keyboard weird things happen: Instead of writing different characters in different cells the graphics engine concatenates the different images of the characters taken from the glyphs and prints them all in every cell. This is what happens.
Empty Grid with selected cell: 
![image](https://user-images.githubusercontent.com/26743415/69021489-91ce4d80-097d-11ea-9b0f-88e6a3de36da.png)

Type "1" on the keyboard:
![image](https://user-images.githubusercontent.com/26743415/69021555-c9d59080-097d-11ea-8c75-d3b203317ac1.png)

Select another cell:
![image](https://user-images.githubusercontent.com/26743415/69021572-e5d93200-097d-11ea-8571-59cb48980100.png)

Type "3" on the keyboard:
![image](https://user-images.githubusercontent.com/26743415/69021626-1751fd80-097e-11ea-8670-6adc4fb5bb26.png)

Repeat: 
![image](https://user-images.githubusercontent.com/26743415/69021661-32247200-097e-11ea-88c0-3e8440dafe6d.png)

And again:
![image](https://user-images.githubusercontent.com/26743415/69021736-7748a400-097e-11ea-808a-4af203581591.png)

Looks like there's a buffer somewhere not emptying? 
Does anybody have an idea of what it can be? The code is the same as in the tutorial.
Appreciate any help, thanks.

**Comment by bvssvni** [comment]
It's weird because `cargo run` seems to work fine here. Does the bug happens in your own project only?

**Comment by kumasan1011** [comment]
Hi.
In my project, this problem is happened.
Maybe, it happens bellow step. 
1. Clone this repository and delete Cargo.lock
2. change the line in main.rs from ".opengl(opengl)" to ".graphics_api(opengl)".
3. cargo run

**Comment by JimmyHypi** [comment]
So apparently as of right now, there's no "opengl()" (in main.rs) function available, I tried to downgrade the version of the crate in the "Cargo.toml" file to what it is in your dependencies, but there was no way to make it work. So what I did is to copy and paste the Cargo.lock file in the repository and keep the "opengl(opengl)" function and it worked, but I haven't checked the differences between the two lock files to be honest, that's really weird.

**Comment by DerekCrosson** [comment]
> So apparently as of right now, there's no "opengl()" (in main.rs) function available, I tried to downgrade the version of the crate in the "Cargo.toml" file to what it is in your dependencies, but there was no way to make it work. So what I did is to copy and paste the Cargo.lock file in the repository and keep the "opengl(opengl)" function and it worked, but I haven't checked the differences between the two lock files to be honest, that's really weird.

Try changing your code to this:
```
let settings = WindowSettings::new("Sudoku", [512; 2])
      .graphics_api(opengl)
      .exit_on_esc(true);
```
