### ISSUE TITLE
Upgrade Tutorial to use new Depenencies

### ISSUE THREAD

**Issue by axelmagn** [PistonDevelopers/Piston-Tutorials#41]
There have been a lot of rearrangements of dependencies recently, especially when it comes to removing reexports in the main piston crate.  This tutorial is failing all over the place.  I tried my hand at fixing it myself, but I don't know the different projects well enough.  bvssvni, would you be able to update  this tutorial now that the crate dependency structure has significantly changed?

**Comment by indiv0** [comment]
@axelmagn @bvssvni I'll handle this.

**Comment by indiv0** [comment]
@axelmagn https://github.com/PistonDevelopers/Piston-Tutorials/issues/42 fixes the tutorial, while [TyOverby/md_rel #4](https://github.com/TyOverby/md_rel/pull/4) fixes the root compilation.
