### ISSUE TITLE
unresolved import: 'std::old_path'

### ISSUE THREAD

**Issue by Plasticcaz** [PistonDevelopers/Piston-Tutorials#43]
I don't know if this is an issue with piston, with the tutorial, or something I'm doing wrong, but when I try to run 'cargo build', I get the following error:

<path>\rustc-serialize-0.2.12\src\serialize.rs:17:5: 17:26 error: unresolved import 'std::old_path'. There is no 'old_path' in 'std'
<path>\rustc-serialize-0.2.12\src\serialize.rs:17: use std::old_path as path;

This would seem to be an issue with the std library, but I only setup rust the other day, so I'd think I'm at the most recent version.

As I said, I don't know if this is an issue with Piston, or with the std library not being completely stable yet, or just my own lack of knowledge in all things rust yet, but some help would be nice.

**Comment by bvssvni** [comment]
Can you post `rustc -V`?

**Comment by Plasticcaz** [comment]
rustc 1.0.0-nightly (eaf4c5c78 2015-02-02 15:04:54 +0000)

**Comment by bvssvni** [comment]
You need the latest nightly, things gets broken all the time.

**Comment by Plasticcaz** [comment]
Thanks. Will do.
