### ISSUE TITLE
Change window backend over to glutin_window.

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/Piston-Tutorials#51]
With SDL2 some users have problems (see PistonDevelopers/opengl_graphics#134).
GLFW didn't work on Ubuntu through error in Unity (see glfw/glfw#368). Fix there are, but users it will be available only in next Ubuntu release.
Is there any reason not to do it?

**Comment by bvssvni** [comment]
There are a few things:

- [ ] glutin_window makes sounds when pressing keys
- [ ] piston-window needs proper handling of retina resolution and mouse coordinate transformation
- [ ] glutin seems to include the window title bar on OSX, which needs to be fixed

**Comment by Potpourri** [comment]
> glutin_window makes sounds when pressing keys
Wow! Interestingly what kind of sounds? It OS X specific bug?

**Comment by bvssvni** [comment]
It is probably OSX specific.

**Comment by mitchmindtree** [comment]
I didn't hear any sounds when I was testing conrod? do you get them if you run the conrod example now? i'm on osx 10.10.2

**Comment by bvssvni** [comment]
I still get beeps on 10.9.5.

**Comment by bvssvni** [comment]
@mitchmindtree It's when I press a key on the keyboard, but not when pressing mouse buttons.

**Comment by mitchmindtree** [comment]
@bvssvni yeah I read your comment in the glutin issue about it, so I tried pressing all my keys while testing conrod but I couldn't hear anything. super strange!

**Comment by bvssvni** [comment]
If I'm the only one with this issue, and if we can fix the other things, then I think we should use glutin.

**Comment by bvssvni** [comment]
The other things are now fixed.

**Comment by Potpourri** [comment]
@bvssvni now I can do it?

**Comment by bvssvni** [comment]
@Potpourri Yes!
