### ISSUE TITLE
square is in the upper-right corner (retina)

### ISSUE THREAD

**Issue by hclarke** [PistonDevelopers/Piston-Tutorials#90]
i copy/pasted from the example, and the square shows up in the corner, instead of the middle.

can be "fixed" by changing
```
c.transform.trans(x, y)
```
to
```
c.transform.trans(x * 0.5,y * 1.5)
```

i'm on osx, with a retina display. my best guess is that the retina scaling is messing up the viewport.

the lower left corner is (0,args.height), and the upper right is (args.width/2, args.height/2)

**Comment by bvssvni** [comment]
I believe this line:

```Rust
let (x, y) = ((args.width / 2) as f64, (args.height / 2) as f64);
```

should be

```Rust
let (x, y) = ((args.draw_width / 2) as f64, (args.draw_height / 2) as f64);
```

**Comment by johnjelinek** [comment]
This isn't fixed for me.
![spinning-square](https://cloud.githubusercontent.com/assets/873610/9426851/77746112-4920-11e5-9514-ec201b0a80f4.gif)

**Comment by knuckolls** [comment]
I fixed the exact problem @johnjelinek is describing in pull request #97.

**Comment by johnjelinek** [comment]
Oh, that makes sense with the pixel doubling.



—
